default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8

development:
  <<: *default
  username: root
  password:
  host: 127.0.0.1
  database: rspec_development

test:
  <<: *default
  username: root
  password:
  host: 127.0.0.1
  database: rspec_test

production:
  <<: *default
  username: root
  password:
  host: 127.0.0.1
  database: rspec_production
